The project has 2 main JAVA files: Client.java and Server.java.
Another file CustomUtil.java is used as reference in both for few operations.

Run instructions:

1. Server

To run Server, open terminal, go to project's bin folder and use below command:
java proj_ftp.Server <portNo> <fileNameToBeCreated> <probability>
eg.
>>>>>java proj_ftp.Server 7735 test_recieve.txt 0.05

2. Client

To run Client, open terminal, go to project's bin folder and use below command
java proj_ftp.Client <host> <portNo> <fileToBeSent> <N> <MSS>
eg.
>>>>>java proj_ftp.Server 192.168.0.7 7735 test_send.txt 10 1000


The file to be send should be in bin folder and the file created is also stored in the bin folder.




